export default{
	showFooter:({commit})=>{
		commit('showFooter')
	},
	hideFooter:({commit})=>{
		commit('hideFooter')
	},
	showBase:({commit})=>{
		commit('showBase')
	},
	hideBase:({commit})=>{
		commit('hideBase')
	},
	showContact:({commit})=>{
		commit('showContact')
	},
	hideContact:({commit})=>{
		commit('hideContact')
	},
	showCerti:({commit})=>{
		commit('showCerti')
	},
	hideCerti:({commit})=>{
		commit('hideCerti')
	},
	showBank:({commit})=>{
		commit('showBank')
	},
	hideBank:({commit})=>{
		commit('hideBank')
	},
	showMobile:({commit})=>{
		commit('showMobile')
	},
	hideMobile:({commit})=>{
		commit('hideMobile')
	},
	showPhone:({commit})=>{
		commit('showPhone')
	},
	hidePhone:({commit})=>{
		commit('hidePhone')
	},
	showConsumer:({commit})=>{
		commit('showConsumer')
	},
	hideConsumer:({commit})=>{
		commit('hideConsumer')
	},
	showBorCer:({commit})=>{
		commit('showBorCer')
	},
	hideBorCer:({commit})=>{
		commit('hideBorCer')
	},

}
